// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALdheOLpz14CPLeo8IaegGiMltZdwx-nc',
    appId: '1:967677225795:web:c628a36237642cf9fc1df6',
    messagingSenderId: '967677225795',
    projectId: 'partytime-46c87',
    authDomain: 'partytime-46c87.firebaseapp.com',
    storageBucket: 'partytime-46c87.firebasestorage.app',
    measurementId: 'G-R2T6S7SS26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYMs7DnanJMrep3ssXNdx_70pj3bnytM',
    appId: '1:967677225795:android:ffd9afe7bd726c0bfc1df6',
    messagingSenderId: '967677225795',
    projectId: 'partytime-46c87',
    storageBucket: 'partytime-46c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3CRz7X5Y6MZG62N0uNTpjF5v-2ys0js',
    appId: '1:967677225795:ios:8b7c83c30d3a121cfc1df6',
    messagingSenderId: '967677225795',
    projectId: 'partytime-46c87',
    storageBucket: 'partytime-46c87.firebasestorage.app',
    iosBundleId: 'com.example.partytime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3CRz7X5Y6MZG62N0uNTpjF5v-2ys0js',
    appId: '1:967677225795:ios:8b7c83c30d3a121cfc1df6',
    messagingSenderId: '967677225795',
    projectId: 'partytime-46c87',
    storageBucket: 'partytime-46c87.firebasestorage.app',
    iosBundleId: 'com.example.partytime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALdheOLpz14CPLeo8IaegGiMltZdwx-nc',
    appId: '1:967677225795:web:a437e586c59508dafc1df6',
    messagingSenderId: '967677225795',
    projectId: 'partytime-46c87',
    authDomain: 'partytime-46c87.firebaseapp.com',
    storageBucket: 'partytime-46c87.firebasestorage.app',
    measurementId: 'G-86N4TQ2TZZ',
  );
}
